import type { Metadata } from "next";
import { inter, openSans, roboto } from "@/lib/util/fonts";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={openSans.className + " antialiased"}>{children}</body>
		</html>
	);
}
